### ISSUE TITLE
Doesn't run upon installation, needs the fuzzywuzzy module

### ISSUE THREAD

**Issue by kalligator** [mathe00/ulauncher-extension-masscode-integration#1]
The extension wouldn't run before installing fuzzywuzzy
`ModuleNotFoundError: No module named 'fuzzywuzzy'`

Solved by running 
`pip install --user fuzzywuzzy`

**Comment by mathe00** [comment]
> The extension wouldn't run before installing fuzzywuzzy `ModuleNotFoundError: No module named 'fuzzywuzzy'`
> 
> Solved by running `pip install --user fuzzywuzzy`

yep I should have mentioned it but there are some libraries required, it's in the [requirements.txt](https://github.com/mathe00/ulauncher-extension-masscode-integration/blob/main/requirements.txt)

**Comment by mathe00** [comment]
the README has been updated and I've also uploaded my new version developed a few days ago with fuzzy search changes and a history feature (but it doesn't work yet...)

**Comment by mathe00** [comment]
it's all good
